Django10/src/Django10/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import handler404,handler500

from bookmark.views import *

#404에러 발생시 호출할 뷰 함수
handler404 = 'Django10.views.handler404'
handler500 = 'Django10.views.handler500'

#handler404 = 'Django10.views.handler404'
#urlpatterns : URL과 뷰함수를 등록 및 관리하는 변수
#URL 등록 시 path함수를 이용해 urlpatterns의 요소를 추가
#path(URL주소(문자열), 뷰함수/클래스 이름) : 등록한 문자열로 클라이언트가 요청시, 뷰함수/클래스가 호출됨
#웹 서버 실행 시 나오는 도메인 주소(127.0.0.1:8000)은 기본값이므로 생략됨
urlpatterns = [
    #127.0.0.1:8000/hello
    path('hello/', admin.site.urls),
    #127.0.0.1:8000 으로 요청시 북마크에 있는 index함수가 호출됨
    path('', index, name='index'),
    #127.0.0.1:8000/booklist/
    path('booklist/',booklist, name='booklist'),
    #127.0.0.1:8000/booklist/1
    #127.0.0.1:8000/booklist/2
    #127.0.0.1:8000/booklist/3
    #URL의 숫자데이터는 'book_id' 매개변수에 저장됨 
    path('booklist/<int:book_id>/', bookdetail, name='bookdetail'),
    #127.0.0.1:8000/vote/ 로 요청하는 모든 URL은 vote폴더안에 있는 urls가 처리함
    path('vote/', include('vote.urls')),
    path('cl/', include('customlogin.urls', namespace='cl' )),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('blog/', include('blog.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
#URL 주소와 실제 저장된 파일 경로를 매칭 및 등록
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)












Django10/src/blog/urls.py
'''
Created on 2018. 11. 3.

@author: user
'''
from django.urls import path
from .views import *
app_name='blog'

urlpatterns=[
    #뷰클래스를 url등록할 때, 뷰클래스명.as_view()로 등록해야함
    path('', Index.as_view(),name='index'),
    path('<int:pk>/',Detail.as_view(), name='detail'),
    path('postR/', PostRegiste.as_view(), name='postR'),
    ]

Django10/src/vote/urls.py
'''
Created on 2018. 10. 21.

@author: user
'''

from django.urls import path
from .views import index, detail, vote, result, questionregister, questionUpdate, questionDelete, choiceDelete, choiceRegiste,choiceUpdate
#app_name : 하위 URL 파일의 그룹이름
app_name = 'vote'
#urlpatterns : path함수를 이용해 url 등록
#도메인 주소 : 127.0.0.1:8000/vote/
urlpatterns = [
    #127.0.0.1:8000/vote/   
    path('', index, name = 'index'),
    path('<int:q_id>/',detail,name='detail'),
    path('vote/',vote, name='vote'),
    path('result/<int:q_id>/', result,name='result'),
    path('questionr/', questionregister, name='qr'),
    path('questionu/<int:question_id>/',questionUpdate, name='qu'),
    #questionDelete 함수 등록하기 별칭 'qd'로 지정하기
    path('questiond/<int:q_id>/', questionDelete,name='qd'),
    path('choided/<int:c_id>/', choiceDelete, name= 'cd'),
    path('choicer/', choiceRegiste, name='cr'),
    path('choiceu/<int:c_id>/', choiceUpdate, name='cu'),
]






Django10/src/vote/models.py
from django.db import models

#질문
#질문제목, 생성일
class Question(models.Model):
    name = models.CharField('설문지 제목',max_length=200)
    date = models.DateTimeField()
    def __str__(self):
        return self.name 
    class Meta:
        ordering = ['-date']
        verbose_name = '질문지'
        verbose_name_plural = '질문지'
#답변항목
#답변내용, 투표수, 어떤질문에 연결되있는지?(외래키)
class Choice(models.Model):
    name = models.CharField('답변항목',max_length=100)
    votes = models.IntegerField('투표 수',default=0)
    question = models.ForeignKey(Question,on_delete = models.CASCADE)
    def __str__(self):
        return self.name + '/' + self.question.name
    class Meta:
        ordering = ['question']
        verbose_name = '답변항목'
        verbose_name_plural = '답변항목'





Django10/src/vote/forms.py
'''
Created on 2018. 10. 27.

@author: user
'''
from django.forms.models import ModelForm

#form : HTML 코드에서 사용할 입력양식(<input>)을 모델클래스에 맞게(또는 커스텀) 자동으로
#만들어주는 기능

#class 클래스명(ModelForm 또는 Form)
#ModelForm : 모델클래스를 기반으로 입력양식을 생성할 때 상속받는 클래스
#Form : 커스텀 입력양식을 생성할 때 상속받는 클래스

#HTML 코드로 변환 시 <p>, <table>, <li> 에 포함된 HTML 문법을 제공함
from .models import Choice, Question #폼 클래스와 연동하기위해 임포트

#Question 모델클래스와 연동된 모델폼클래스 정의
class QuestionForm(ModelForm):
    class Meta: #Meta 클래스 정의를 통해서 모델 클래스에 관한 정보를 입력
        #model : 어떤 모델클래스와 연동되는지 작성
        #fields : 모델클래스의 어떤 변수를 입력양식으로 만들것인지 지정하는 변수(iterable)
        #exclude : 모델클래스의 어떤 변수를 입력양식에서 제외할 것인지 지정하는 변수(iterable)
        #fields, exclude 변수 중 한개만 사용해야함
        
        model = Question #해당 모델폼이 Question 모델클래스와 연결하도록 설정
        fields = ['name']#Question 모델클래스에서 name변수만 입력양식으로 제공
        #exclude = ['date'] #Question 모델클래스에서 date변수를 제외하고 입력양식을 제공

#Choice 모델클래스와 연동된 모델폼클래스 정의 
class ChoiceForm(ModelForm):
    def __init__(self, *args, **kwargs):
        #ModelForm 클래스의 생성자를 호출해 모델폼의 기능을 할 수 있도록 초기화
        super().__init__(*args,**kwargs)
        #question 라벨 이름을 한글로 수정
        self.fields['question'].label = "질문지"
        
    class Meta:
        #Choice 모델클래스와 연동
        #name, question 변수를 입력양식으로 제공할 수 있도록 설정
        model = Choice
        fields = ['question','name']
        #exclude = ['votes']













Django10/src/vote/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice

from django.http.response import HttpResponseRedirect
from django.urls import reverse
#return HttpResponseRedirect(URL 문자열) : URL 문자열을 리다이렉트 해주는 클래스
#ex) return HttpResponseRedirect('127.0.0.1:8000/vote/')
#-> 웹클라이언트는 HTML문서가 아닌 '127.0.0.1:8000/vote/' 주소를 받음. 받은 주소로 서버에 재요청함

#reverse(별칭 문자열) : 해당별칭을 가진 URL을 반환함
#ex) reverse('vote:index') -> '127.0.0.1:8000/vote/' 를 반환

#return HttpResponseRedirect( reverse( '별칭 문자열' ) )

from django.contrib.auth.decorators import login_required



#index(질문 리스트)
def index(request):
    #Question 객체들을 추출
    objs = Question.objects.all()
    #render 호출 및 수정된 html 문서 반환
    return render(request, 'vote/index.html', { 'a' : objs })

#detail(질문 선택 시 답변항목 제공)
def detail(request, q_id):
    obj = get_object_or_404(Question, id = q_id) #id와 pk는 동일한 의미 #pk=q_id
    return render(request,'vote/detail.html', {'q' : obj } )

#vote(웹 클라이언트의 요청에 따라 투표수 증가)
def vote(request):
    if request.method == "POST": #사용자 요청이 post방식인 경우에 투표 처리를 함
        #request.POST : POST방식으로 요청하면서 넘어온 데이터의 집합
        #request.POST.get(키값) : 키값은 입력양식의  name 속성에 문자열과 동일하게 작성
        c_id = request.POST.get('select')
        #Choice 객체 중 id 변수값이 c_id와 동일한 객체를 찾아 추출
        c = get_object_or_404(Choice, id = c_id)
        c.votes += 1 #해당 객체의 votes 변수값을 1증가
        c.save()     #변동사항을 데이터베이스에 반영
        #결과 뷰의 URL을 반환
        return HttpResponseRedirect( 
               reverse('vote:result', args=(c.question.id,))  )
    else: #잘못된 클라이언트 접근 처리
        # 'vote:index' 별칭을 가진 URL을 찾아 웹 클라이언트에게 전달
        return HttpResponseRedirect( reverse('vote:index')  )

#result(투표 결과 화면)
def result(request, q_id):
    obj = get_object_or_404(Question, id = q_id)
    return render(request, 'vote/result.html', {'q' : obj})

from .forms import QuestionForm, ChoiceForm #모델폼클래스를 사용하기 위해서 임포트
from _datetime import datetime #현재 날짜/시간을 불러오는 파이썬 모듈

#질문 등록 뷰
@login_required
def questionregister(request):
    if request.method == "GET":#클라이언트가 해당 뷰를 처음 호출했을 경우
        #폼클래스의 객체 생성. 인자값을 전달하지 않은경우 입력양식에 값이 비어있는 형태의 객체를 생성 
        form1 = QuestionForm()  
        print( form1.as_p() )
        
        return render(request, 'vote/qr.html', {'a' : form1 })
    elif request.method == "POST":#클라이언트가 해당 뷰로 데이터를 보낸 경우
        #request.POST : POST방식으로 요청한 클라이언트의 데이터가 들어있는 변수
        #사용자 입력을 해당 폼객체 생성시 넣을 수 있음
        form1 = QuestionForm( request.POST )
        if form1.is_valid(): #사용자가 입력한 값이 유효한 값인지 확인
            #폼객체.cleaned_data : is_valid() 함수로 유효한 값인지 확인한 후 True가 반환됬을 때,
            #사용자의 입력정보를 확인할 수 있는 사전형 변수 
            print ('등록하려는 설문지 제목',  form1.cleaned_data['name'])
            #폼객체.save() : 사용자가 입력한 데이터를 기반으로 연결된 모델클래스의 객체를 데이터베이스에 생성
            #form1.save() -> 사용자가 입력한 데이터로 Question 객체 생성/반환 및 데이터베이스에 저장
            #form1.save(commit = False) -> 사용자가 입력한 데이터로 Question 객체 생성 및 반환
            
            #Question 객체는 date 변수에 값이 비어있으면 안되므로, 파이썬 코드로 변수값을 채워준 뒤에 저장해야함
            q = form1.save(commit = False) #QuestionForm 객체로 Question객체를 생성(데이터베이스저장X)     
            print('생성된 Question 객체', q)
            q.date = datetime.now() #파이썬 모듈을 이용해서 현재시간을 Question객체의 date변수에 저장
            q.save()                #생성된 새로운 Question 객체를 데이터베이스에 저장
            
            #객체 생성이 끝난 후 vote그룹의 index 별칭의 URL을 클라이언트에게 전달
            return HttpResponseRedirect( reverse('vote:index') )
        else: #사용자가 입력한 값이 유효한 값이 아닌경우에 대한 처리
            #사용자가 입력한 데이터를 바탕으로 입력양식을 제공하는 HTML 문서 전달
            return render(request, 'vote/qr.html', {'a' : form1,
                                                    'error' : "유효하지않은 값을 작성했습니다." })
#질문 수정 뷰
#어떤 Question 객체를 수정 요청했는지 알아야하므로 매개변수 추가
@login_required
def questionUpdate(request, question_id):
    obj = get_object_or_404(Question, id = question_id)
    if request.method == "GET":
        #데이터베이스에 저장된 Question객체의 정보를 기반으로 모델폼 객체를 생성
        form1 = QuestionForm(instance = obj)
        return render(request, "vote/qu.html", {'b' : form1})
    elif request.method == "POST":
        #기존 객체에 저장된 정보를 사용자의 입력 데이터로 변경한 모델폼 객체를 생성
        form1 = QuestionForm(request.POST, instance = obj)
        if form1.is_valid():#수정한 값이 유효한 값인지 확인
            #모델 폼 객체와 연결된 모델 객체의 데이터를 변경해 데이터베이스에 저장
            b = form1.save() #변경할 사항이 없으므로 save함수 호출해 데이터베이스에 저장
            print(obj)
            print(b)
            return HttpResponseRedirect( reverse('vote:detail', args=(b.id,) ) )
        else:
            return render(request, 'vote/qu.html', {'b': form1})
#질문 삭제 뷰
@login_required
def questionDelete(request, q_id):
    #삭제할 객체 찾기
    obj = get_object_or_404(Question, id = q_id)
    obj.delete() #해당 객체를 데이터베이스에서 삭제함. 객체를 활용할 수 있음
    
    return HttpResponseRedirect( reverse('vote:index') )

#답변 등록 
#매개변수가 필요없음
@login_required
def choiceRegiste(request): #Template 추가, URL 등록, Form 수정
#GET/POST 분리
    if request.method == "GET":
        #GET-> 비어있는 ChoiceForm 객체 생성 -> HTML 전달
        a = ChoiceForm()
        return render(request, 'vote/cr.html', {'a' : a })
    elif request.method == "POST":
        #POST-> 사용자 입력데이터를 기반으로 ChoiceForm 객체 생성 
        #    -> 유효한 값인지 확인 -> 객체 변환 및 데이터베이스에 저장 -> index 또는 detail URL을 반환
        a = ChoiceForm(request.POST)
        if a.is_valid():
            b = a.save()
            #return HttpResponseRedirect( reverse('vote:index')) #index
            return HttpResponseRedirect( reverse('vote:detail' , args=(b.question.id ,) ))
        else:
            return render(request, 'vote/cr.html', {'a' : b })
#답변 삭제
#1)매개 변수를 추가(어떤 답변항목을 삭제할 것인가?)
@login_required
def choiceDelete(request, c_id):
#2)매개 변수로 Choice 객체 찾기
    c = get_object_or_404(Choice, id = c_id)
#3)해당 객체를 삭제
    c.delete()
#4)index 또는 detail의 URL을 반환
    #return HttpResponseRedirect( reverse('vote:index')) #index
    return HttpResponseRedirect( reverse('vote:detail', args=(c.question.id ,)))  #detail


#답변 수정 (내일)
#매개변수 추가(어떤 답변항목을 수정할 것인가?)
@login_required
def choiceUpdate(request, c_id):
    #Choice 객체 찾기
    c = get_object_or_404(Choice, id = c_id)
    #GET/ POST 분리
    if request.method == "GET":
        #GET -> Choice 객체를 기반으로 ChoiceForm 생성 -> HTML 전달
        cf = ChoiceForm(instance = c)
        return render(request, 'vote/cr.html', {'a': cf})
    elif request.method == "POST":
        #POST -> 사용자 입력데이터 + Choice 객체를 기반으로 ChoiceForm 생성 -> 유효한 값인지 확인 -> 객체저장->URL반환
        cf = ChoiceForm(request.POST, instance= c)
        if cf.is_valid():
            cf.save()
            return HttpResponseRedirect( reverse( 'vote:detail', args=(c.question.id,) ) )
        else:
            return render(request, 'vote/cr.html', {'a' : cf, 'error' : '유효한 값이 아닙니다.'})



















Django10/src/vote/templates/vote/cr.html
{%extends 'base.html' %}
{%block title%}
답변항목
{%endblock%}
{% block content %}
	<!-- 에러 발생 시 보여지는 부분 -->
	{% if error %}
		<h1>{{error}}</h1>
	{% endif %}
	
	<!-- 답변 추가/수정에 사용되는 HTML -->
	<form action="" method = post>
		{% csrf_token %}
		<table>
			{{ a.as_table }}
		</table>
		<input type='submit' value="제출">
	</form>
{% endblock %}

Django10/src/vote/templates/vote/detail.html
{%extends 'base.html' %}
{%block title%}
설문조사 상세보기
{%endblock%}
{% block content %}
	<h1>{{ q.name }}</h1>
	<form action="{% url 'vote:vote' %}" method ="post">
		{# csrf_token : csrf(외부 사이트에서 입력양식으로 접근) 공격 방지 #}
		{% csrf_token %}
		{# 모델클래스명A.모델클래스명B_set : A모델클래스와 연결된 B 객체들을 대상으로 추출 #}
		{% for c in q.choice_set.all  %}
			<!-- forloop.counter : 현재 반복문이 반복된 횟수를 저장한 변수 -->
			<!-- q.choice_set.all : q(Question객체)와 연결된 choice객체들을 모두 추출 -->
			<input type="radio" id='a{{forloop.counter}}' 
			       name='select' value="{{ c.id }}">
			<label for = 'a{{forloop.counter}}'> {{ c.name }} </label>
			<a href="{% url 'vote:cu' c.id %}">수정</a>
			<a href="{% url 'vote:cd' c.id %}">삭제</a>
			<br>
		{% endfor %}
		<input type="submit" value="투표">
	</form>
	<br>
	<a href="{% url 'vote:qu' q.id %}">해당 설문조사 수정</a>
	<br>
	<a href="{% url 'vote:qd' q.id %}">해당 설문조사 삭제</a>
{% endblock %}






Django10/src/vote/templates/vote/index.html
{%extends 'base.html' %}
{%block title%}
설문조사 목록
{%endblock%}
{% block content %}
	<table width=100%>
		<caption>설문조사목록</caption>
		<tr>
			<th> 질문지 </th>
			<th> 생성일 </th>
		</tr>
	{% for obj in a %}
		<tr>
			<th> <a href="{% url 'vote:detail' obj.id %}">{{ obj.name }}</a> </th>
			<th> {{ obj.date }} </th>
		</tr>
	{% endfor   %}
	</table>
	
	<!-- 설문조사 등록 링크 -->
	<a href="{% url 'vote:qr' %}">설문지 생성하기</a>
	<a href="{% url 'vote:cr' %}">답변항목 생성하기</a>
{% endblock %}






Django10/src/vote/templates/vote/qr.html
{%extends 'base.html' %}
{%block title%}
설문조사 등록
{%endblock%}
{% block content %}
	<h1>설문조사 등록</h1>
	<form action="" method="post">
		{% csrf_token %}
		<!-- a == QuestionForm 객체
		a.as_p == 파이썬 코드에서 a.as_p() 동일
		as_p : <p> </p> 사이에 <input>와 <label>를 넣는 형식으로 HTML 코드를 생성  -->
		{{ a.as_p }} 
		<input type="submit" value="질문글 쓰기">
	</form>
{% endblock %}






Django10/src/vote/templates/vote/qu.html
{%extends 'base.html' %}
{%block title%}
설문조사 수정 
{%endblock%}
{% block content %}
	<h1>설문조사 수정</h1>
	<form action="" method="post">
		{% csrf_token %}
		<table>
			{{ b.as_table }}
		</table>
		<input type="submit" value="수정">
	</form>
{% endblock %}

Django10/src/vote/templates/vote/result.html
{%extends 'base.html' %}
{%block title%}
투표 결과
{%endblock%}
{% block content %}
	<h1>{{q.name}}의 투표결과</h1>
	<table>
		<tr>
			<th>답변항목</th>
			<th>투표 수</th>
		</tr>
		{% for c in q.choice_set.all %}
			<tr>
				<th>{{c.name}}</th>
				<th>{{c.votes}}</th>
			</tr>
		{% endfor %}
	</table>
	<a href="{% url 'vote:index' %}"> 설문리스트로 돌아가기 </a>
{%endblock%}


