Django10/src/Django10/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import handler404,handler500

from bookmark.views import *

#404에러 발생시 호출할 뷰 함수
handler404 = 'Django10.views.handler404'
handler500 = 'Django10.views.handler500'

#handler404 = 'Django10.views.handler404'
#urlpatterns : URL과 뷰함수를 등록 및 관리하는 변수
#URL 등록 시 path함수를 이용해 urlpatterns의 요소를 추가
#path(URL주소(문자열), 뷰함수/클래스 이름) : 등록한 문자열로 클라이언트가 요청시, 뷰함수/클래스가 호출됨
#웹 서버 실행 시 나오는 도메인 주소(127.0.0.1:8000)은 기본값이므로 생략됨
urlpatterns = [
    #127.0.0.1:8000/hello
    path('hello/', admin.site.urls),
    #127.0.0.1:8000 으로 요청시 북마크에 있는 index함수가 호출됨
    path('', index, name='index'),
    #127.0.0.1:8000/booklist/
    path('booklist/',booklist, name='booklist'),
    #127.0.0.1:8000/booklist/1
    #127.0.0.1:8000/booklist/2
    #127.0.0.1:8000/booklist/3
    #URL의 숫자데이터는 'book_id' 매개변수에 저장됨 
    path('booklist/<int:book_id>/', bookdetail, name='bookdetail'),
    #127.0.0.1:8000/vote/ 로 요청하는 모든 URL은 vote폴더안에 있는 urls가 처리함
    path('vote/', include('vote.urls')),
    path('cl/', include('customlogin.urls', namespace='cl' )),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('blog/', include('blog.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
#URL 주소와 실제 저장된 파일 경로를 매칭 및 등록
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)












Django10/src/blog/urls.py
'''
Created on 2018. 11. 3.

@author: user
'''
from django.urls import path
from .views import *
app_name='blog'

urlpatterns=[
    #뷰클래스를 url등록할 때, 뷰클래스명.as_view()로 등록해야함
    path('', Index.as_view(),name='index'),
    path('<int:pk>/',Detail.as_view(), name='detail'),
    path('postR/', PostRegiste.as_view(), name='postR'),
    ]

Django10/src/blog/models.py
from django.db import models

#카테고리
class PostType(models.Model):
    name = models.CharField('카테고리', max_length=20)
    def __str__(self):
        return self.name
    
from django.conf import settings
#글(제목,글쓴이, 글내용, 작성일, 카테고리)
class Post(models.Model):
    type = models.ForeignKey(PostType, on_delete = models.PROTECT)
    #models.CASCADE : 연결된 객체가 삭제되면 다같이 삭제됨
    #models.PROTECT : 연결된 객체가 삭제되는것을 막아줌
    #models.SET_NULL : 연결된 객체가 삭제되면 null 값을 가짐
    #models.SET_DEFAULT : 연결된 객체가 삭제되면 기본 객체와 연결됨
    #models.SET(연결할 객체) : 연결된 객체가 삭제되면 매개변수로 지정된 객체로 값이 변경
    headline = models.CharField('제목', max_length=200)
    #TextField : 글자수 제한이 없는 문자열을 저장하는 공간
    #null : 데이터베이스에 저장할 때 해당 변수 값이 비어있어도 생성되도록 허용
    #blank : 폼객체.is_valid(), 폼객체.as_p 을 사용할 때 빈칸을 허용
    content = models.TextField('내용', null=True, blank=True)
    #settings.AUTH_USER_MODEL : 현재 웹서버가 회원을 관리할 때 사용하는 모델클래스를 의미
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    #DateTimeField의 매개변수 auto_now_add : 객체가 생성될때 자동으로 서버의 현재시간을 저장할 수 있도록 허용
    pub_date = models.DateTimeField('작성일', auto_now_add=True)
    
    class Meta:
        #ordering : 데이터베이스에 저장된 객체를 정렬하는 방식을 저장
        #변수이름 앞에 '-'를 붙인 경우 내림차순으로 정렬
        ordering = ['-id'];

#이미지
class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField('이미지파일', upload_to = 'images/%Y/%m/%d')
    #ImageField: 이미지 경로를 저장하는 저장공간
    #upload_to : 실제 이미지를 저장할때 사용할 경로
    #%Y : 해당 서버의 년도 %m : 해당 서버의 월 %d : 해당 서버의 일
    
    #객체 삭제 시 호출되는 함수. 여기에 실제 이미지를 지우는 과정을 코딩
    def delete(self, using=None, keep_parents=False):
        self.image.delete() #image 변수에 저장된 경로에 파일을 삭제
        return models.Model.delete(self, using=using, keep_parents=keep_parents)
    
#파일
class PostFile(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = models.FileField('첨부파일', upload_to = 'files/%Y/%m/%d')
    #FileField : 파일(이미지,실행파일,액셀,워드, 등) 의 경로를 저장하는 공간
    
    def delete(self, using=None, keep_parents=False):
        self.file.delete()
        return models.Model.delete(self, using=using, keep_parents=keep_parents)












Django10/src/blog/forms.py
'''
Created on 2018. 11. 4.

@author: user
'''
from django.forms.models import ModelForm
from .models import Post
from django import forms
class PostForm(ModelForm):
    
    files = forms.FileField(required=False, 
                            widget=forms.ClearableFileInput(attrs={'multiple':True}))
    images = forms.ImageField(required=False,
                              widget=forms.ClearableFileInput(attrs={'multiple':True}))
    class Meta:
        model = Post
        fields=['type', 'headline', 'content']
        
        
        
        
        
        

Django10/src/blog/views.py
from django.shortcuts import render
from django.views.generic.list import ListView

#제네릭뷰 : 장고에서 제공하는 여러가지 뷰 기능을 수행하는 클래스
#class 뷰이름(제네릭뷰 상속):
#상속받은 제네릭뷰 클래스의 변수/메소드를 수정해 사용
#단, 해당 제네릭뷰가 어떤 기능을 수행하는지, 어떤변수/함수를 사용할 수 있는지 파악해야함
#ListView   : 특정 모델클래스의 객체의 목록을 다루는 기능을 수행하는 뷰클래스
#DetailView : 특정 모델클래스의 객체 하나를 템플릿에 전달할때 사용하는 뷰클래스
from .models import Post,PostFile,PostImage

from django.views.generic.detail import DetailView


# 게시물 목록 (index)
class Index(ListView):
    template_name = 'blog/index.html' #HTML 파일의 경로를 저장하는 변수
    model = Post         #목록으로 보여질 모델클래스를 저장하는 변수
    context_object_name = 'post_list' #템플릿에 객체를 넘겨줄때 사용할 변수이름(사전형 키값)
    paginate_by = 5          #한페이지에 몇개의 객체를 보여줄지 설정
    
# 상세 페이지 (detail)
class Detail(DetailView):
    template_name = 'blog/detail.html'
    model = Post
    context_object_name = 'obj'

from django.http.response import HttpResponseRedirect
from django.urls.base import reverse


from .forms import PostForm
from django.contrib.auth.mixins import LoginRequiredMixin #비로그인상태의 유저를 로그인페이지로 이동
from django.views.generic.edit import FormView         #폼클래스를 객체로 생성해 템플릿으로넘겨주는 뷰
#글 등록 페이지 (PostRegist)
class PostRegiste(LoginRequiredMixin, FormView):
    template_name = 'blog/postregiste.html'
    form_class = PostForm
    context_object_name = 'form'
    #FormView 는 내부적으로 GET방식으로 요청한 클라이언트에게 지정된 폼클래스의 객체를 넘겨줌
    #POST방식으로 요청한 클라이언트를 구분하며 is_valid까지 수행을 함
    
    #is_valid()함수가 True를 반환했을 때에 대한 처리를 오버라이딩으로 구현
    
    def form_valid(self, form):
        obj = form.save(commit=False) #obj : Post 객체 (데이터베이스에 저장 X) 
        obj.author = self.request.user #유저정보 채우기
        obj.save()                      #데이터베이스에 Post객체 저장
        
        #사용자가 저장요청한 이미지파일, 파일을 객체로 만들어 저장
        #<form> 태그 중 name이 'images'인 파일데이터를 추출하는 방식
        for f in self.request.FILES.getlist('images'):
            #PostImage 객체를 생성
            #객체 생성 시 각 변수에 값을 채워넣는 작업을 수행함
            image = PostImage(post=obj, image=f)
            #image = PostImage()
            #image.post = obj
            #image.image = f
            image.save()
        for f in self.request.FILES.getlist('files'):
            file = PostFile(post=obj, file=f)
            file.save()
            
        return HttpResponseRedirect( reverse('blog:detail', args=(obj.id,) ) )














Django10/src/blog/templates/blog/detail.html
{% extends 'base.html' %}
{% block title %}
{{obj.headline}}
{% endblock %}
{% block content %}
<table width="90%">
	<tr>
		<th>제목</th>
		<th>{{obj.headline}}</th>
	</tr>
	<tr>
		<th>글쓴이/작성일</th>
		<th>{{obj.author}}/{{obj.pub_date}}</th>
	</tr>
	<tr>
		<th colspan="2">
			<!-- Post 객체와 연결된 이미지, 파일 출력 -->
			{% for i in obj.postimage_set.all %}
				<img src="{{ i.image.url }}" width = 30%>
			{%endfor%}
			{% for f in obj.postfile_set.all %}
				<a href="{{ f.file.url}}" download>첨부파일{{forloop.counter}}</a>
			{% endfor %}
			<pre>{{obj.content}}</pre>
		</th>
	</tr>
</table>
{% endblock %}

Django10/src/blog/templates/blog/index.html
{% extends 'base.html' %}
{% block title %}
게시판
{% endblock %}

{% block content %}
{# post_list : Post 객체 리스트 #}
{# page_obj : 페이지 관련 객체 #}
{# page_obj.has_previous : 이전 페이지가 존재하는지 확인하는 함수 #}
{# page_obj.has_next  : 다음 페이지가 존재하는지 확인하는 함수 #}
<!-- 이전페이지, 다음페이지가 존재하는지 확인 후 링크 생성 -->
{% if page_obj.has_previous %}
<!-- 현재 페이지에 GET방식으로 재요청. page 변수에 들어있는 값에 해당하는 페이지로 이동-->
	<a href="?page={{page_obj.previous_page_number}}">이전페이지</a>
{% endif %}
{% if page_obj.has_next %}
	<a href="?page={{page_obj.next_page_number}}">다음페이지</a>
{% endif %}

<table width="90%">
	<tr>
		<th>글번호</th>
		<th>제목</th>
		<th>작성자</th>
		<th>작성일</th>
	</tr>
	{% for post in post_list %}
		<tr>
			<th>{{post.id}}</th>
			
			<th>
				<a href="{% url 'blog:detail' post.id %}">{{post.headline}}</a>
			</th>
			
			<th>{{post.author}}</th>
			<th>{{post.pub_date}}</th>
		</tr>
	{% endfor%}
</table>

<a href="{% url 'blog:postR' %}">글쓰기</a>







{% endblock %}

Django10/src/blog/templates/blog/postregiste.html
{% extends 'base.html' %}

{% block title %}
글쓰기
{% endblock%}

{% block content %}
<form action ="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<table>
		{{form.as_table}}
	</table>
	<input type="submit" value="글쓰기">
</form>
{% endblock %}