Django10/src/Django10/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import handler404,handler500

from bookmark.views import *

#404에러 발생시 호출할 뷰 함수
handler404 = 'Django10.views.handler404'
handler500 = 'Django10.views.handler500'

#handler404 = 'Django10.views.handler404'
#urlpatterns : URL과 뷰함수를 등록 및 관리하는 변수
#URL 등록 시 path함수를 이용해 urlpatterns의 요소를 추가
#path(URL주소(문자열), 뷰함수/클래스 이름) : 등록한 문자열로 클라이언트가 요청시, 뷰함수/클래스가 호출됨
#웹 서버 실행 시 나오는 도메인 주소(127.0.0.1:8000)은 기본값이므로 생략됨
urlpatterns = [
    #127.0.0.1:8000/hello
    path('hello/', admin.site.urls),
    #127.0.0.1:8000 으로 요청시 북마크에 있는 index함수가 호출됨
    path('', index, name='index'),
    #127.0.0.1:8000/booklist/
    path('booklist/',booklist, name='booklist'),
    #127.0.0.1:8000/booklist/1
    #127.0.0.1:8000/booklist/2
    #127.0.0.1:8000/booklist/3
    #URL의 숫자데이터는 'book_id' 매개변수에 저장됨 
    path('booklist/<int:book_id>/', bookdetail, name='bookdetail'),
    #127.0.0.1:8000/vote/ 로 요청하는 모든 URL은 vote폴더안에 있는 urls가 처리함
    path('vote/', include('vote.urls')),
    path('cl/', include('customlogin.urls', namespace='cl' )),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('blog/', include('blog.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
#URL 주소와 실제 저장된 파일 경로를 매칭 및 등록
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)












Django10/src/blog/urls.py
'''
Created on 2018. 11. 3.

@author: user
'''
from django.urls import path
from .views import *
app_name='blog'

urlpatterns=[
    #뷰클래스를 url등록할 때, 뷰클래스명.as_view()로 등록해야함
    path('', Index.as_view(),name='index'),
    path('<int:pk>/',Detail.as_view(), name='detail'),
    path('postR/', PostRegiste.as_view(), name='postR'),
    ]

Django10/src/vote/urls.py
'''
Created on 2018. 10. 21.

@author: user
'''

from django.urls import path
from .views import index, detail, vote, result, questionregister, questionUpdate, questionDelete, choiceDelete, choiceRegiste,choiceUpdate
#app_name : 하위 URL 파일의 그룹이름
app_name = 'vote'
#urlpatterns : path함수를 이용해 url 등록
#도메인 주소 : 127.0.0.1:8000/vote/
urlpatterns = [
    #127.0.0.1:8000/vote/   
    path('', index, name = 'index'),
    path('<int:q_id>/',detail,name='detail'),
    path('vote/',vote, name='vote'),
    path('result/<int:q_id>/', result,name='result'),
    path('questionr/', questionregister, name='qr'),
    path('questionu/<int:question_id>/',questionUpdate, name='qu'),
    #questionDelete 함수 등록하기 별칭 'qd'로 지정하기
    path('questiond/<int:q_id>/', questionDelete,name='qd'),
    path('choided/<int:c_id>/', choiceDelete, name= 'cd'),
    path('choicer/', choiceRegiste, name='cr'),
    path('choiceu/<int:c_id>/', choiceUpdate, name='cu'),
]






Django10/src/bookmark/models.py
from django.db import models
#모델 : 데이터베이스에 데이터를 저장할 때, 어떤 형식으로 저장할지 관리 및 정의 부분
#Model 상속받으면서 클래스를 정의

#Model 클래스 정의 후, makemigrations 를 통해 migration 파일을 생성
#생성한 파일로 migrate 를 통해 데이터베이스에 저장공간 생성 됨
# 클래스 정의 -> makemigrations -> migrate 순으로 진행됨


#북마크 모델 클래스
#이름 및 URL 저장
class BookMark(models.Model):
    #해당 모델클래스에 저장할 값을 정의할 때, 클래스 내의 변수를 정의
    #models.py에 있는 XXXField 클래스의 객체를 변수에 저장하는 것으로 정의할 수 있음
    #이름 저장
    #CharField : 글자수 제한이 있는 문자열을 저장하는 공간 정의
    bookname = models.CharField(max_length=200)
    #URL 저장
    #URLField : 인터넷 주소(URL)을 저장하는 공간 정의
    bookurl = models.URLField()
    #__str__ : 객체를 출력할 때 표현방식을 처리하는 파이썬 함수
    #print(북마크객체) -> 해당 객체의 bookname 변수에 저장된 문자열 출력
    def __str__(self):
        return self.bookname
    # 모델클래스를 정렬, 보여지는 이름을 변경할 때 Meta 클래스를 정의해 사용할 수 있음
    class Meta:
        ordering = ('bookname',) #정렬방식을 bookname변수의 값을 오름차순으로 정렬
        #내림차순으로 정렬 하고 싶은 경우 변수명 앞에 '-' 붙이기
    
    
    
    
    
    
    
    
    
    

Django10/src/bookmark/views.py
from django.shortcuts import render

#View : 사용자의 요청에 따라 처리하고, HTML 문서나 새로운 URL 주소를 전송 역할

#View 정의 시 클래스/함수 형태로 정의

#View 함수 정의 시 첫번째 매개변수로 request를 반드시 사용함
#request : 사용자의 요청 정보, <form>으로 넘겨준 데이터, 로그인정보, 세션정보, 요청방식(GET,POST)

#HTML 전송하는 메인페이지
def index(request):
    #render(request, HTML문서의 경로, HTML문서에 전달할 값(사전형) )
    #현재 요청을 한 웹 클라이언트에게 HTML 파일을 전달하는 함수
    #HTML 문서에게 값을 전달하고 싶은 경우 3번째 매개변수에 사전형으로 값을 전달할 수 있음
    #사전형에서 사용한 '키'값은 HTML문서 내에서 변수이름처럼 사용 가능 
    
    return render(request, 'bookmark/index.html',{ 'a' : 'Hello Django',
                                                  'b' : [1,2,3] })
#해당 모델클래스에 저장된 객체들을 추출하기 위해서 임포트
from .models import BookMark

#북마크 모델클래스에 저장된 객체를 HTML 문서에 전달하는 기능
def booklist(request):
    #모델클래스명.objects.all() : 데이터베이스에 해당 모델클래스로 저장된 모든 객체를 리스트 형태 추출
    #모델클래스명.objects.get() : 해당 모델클래스에 객체 중 특정 조건을 만족하는 객체 1개를 추출 
    #모델클래스명.objects.filter() : 특정 조건을 만족하는 다수의 객체를 리스트형태로 추출
    #                 .exclude() : 특정 조건을 만족하지않는 다수의 객체를 리스트형태로 추출
    
    objs = BookMark.objects.all() #데이터베이스에 저장된 BookMark 모델클래스의 객체를 모두 추출
    
    return render(request,'bookmark/booklist.html', {'list' : objs })

#북마크 객체에 저장된 값 하나를 출력하는 뷰 기능
#뷰함수에서 URL에 특정 영역을 매개변수로 활용할 수 있음
def bookdetail(request, book_id ):
    #get : 객체 한개를 추출
    #get함수의 인자값은 해당 모델클래스의 변수명을 사용
    #객체들을 식별하기 위한 id변수가 자동으로 생성되 특정객체를 추출할 때 사용할 수 있음
    #조건을 만족하는 객체가 한개도 없는 경우, 서버에러가 발생함
    
    #북마크 객체중 한개를 추출
    #북마크 객체들 중 id변수에 book_id값과 동일한 객체 한개를 추출
    obj = BookMark.objects.get(id=book_id)
    #HTML 문서에 추출한 객체를 넘겨줌
    return render(request, 'bookmark/bookdetail.html', {'obj' : obj })









Django10/src/bookmark/templates/bookmark/bookdetail.html
{% extends 'base.html' %}
{% block title %}
북마크 상세보기
{% endblock%}
{% block content %}
	{# 해당 HTML은 obj 변수를 사용가능. obj = 북마크 객체 #}
	<h1>{{ obj.bookname }}</h1>
	<h2>해당객체의 ID값 : {{ obj.id }}</h2>
	<h2>해당객체의 URL : {{ obj.bookurl }}</h2>
	<P> 객체가 저장하지 않은 변수 호출 : {{ obj.a }} </P>
	<p> 뷰에서 넘겨주지 않은 변수 호출 : {{ b }} </p>
{% endblock %}

Django10/src/bookmark/templates/bookmark/booklist.html
{%extends 'base.html' %}
{% block title %}
북마크 리스트
{% endblock %}
{% block content %}
	<h1> BookMark 모델 클래스에 저장된 객체 리스트</h1>
	{# list : 뷰에서 넘겨준 북마크 객체 리스트 #}
	{# obj : 북마크 객체. obj.bookname / obj.bookurl 로 객체가 저장한 변수값을 추출 #}
	<ol>
		{% for obj in list  %}
			<li>
				<a href="{% url 'bookdetail' obj.id %}">{{obj.bookname}}</a> 
				: 
				<a href=" {{ obj.bookurl }} ">바로가기</a> 
			</li>
		{% endfor %}
	</ol>
	<a href="{% url 'index' %}">메인페이지로 가기</a>
{% endblock %}

Django10/src/bookmark/templates/bookmark/index.html
{% extends 'base.html' %}

{% block content %}
	<!-- HTML내에 주석처리 -->
	<p> 첫 웹 서버 프로젝트를 생성하고 북마크 어플리케이션을 만듦 </p>
	{# 파이썬 코드로 주석을 기입함 #}
	{# 변수/함수반환값을 출력할 때는 중괄호 두개 '{{}}' 를 사용 if, for 사용 시 '{%%}' 를 사용      #}
	
	{# for, if 문 사용 시 endfor, endif를 적어서 영역을 지정해야 함. 뷰에서 넘겨준 사전형은 키값을 변수처럼 사용할 수 있음 #}
	{# HTLM 내에서 함수 호출 시 소괄호 입력 X. 때문에 매개변수가 필요한 함수는 사용할 수 없음 #}
	<p> a변수안에 들어있는 값 : {{ a }} </p>
	<ul>
		{% for i in b %}
			<li>{{i}} </li>
		{% endfor %}
	</ul>
	<a href="{% url 'booklist' %}">북마크 리스트 보기</a>
	{# url '뷰의 별칭' 매개변수값1 매개변수값2 ...  -> 해당 별칭을 가진 url을 찾아 설정하는 문법 #}
	{# 하위 urlConf에 접근할 시 해당 url의 app_name을 앞에 적어야함 #}
	<a href="{% url 'vote:index' %}">설문조사 바로가기</a>
{% endblock %}






